# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-11 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geospace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': 'geospaces',
            },
        ),
        migrations.CreateModel(
            name='Intrusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_datetime', models.DateTimeField()),
                ('verified_datetime', models.DateTimeField()),
                ('neutralized_datetime', models.DateTimeField()),
                ('non_human_intrusion_datetime', models.DateTimeField()),
                ('status', models.CharField(max_length=25)),
                ('duration', models.FloatField()),
            ],
            options={
                'ordering': ['-detected_datetime'],
                'db_table': 'intrusions',
                'get_latest_by': 'detected_datetime',
            },
        ),
        migrations.CreateModel(
            name='Morcha',
            fields=[
                ('name', models.CharField(max_length=250, verbose_name='name of morcha')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('slug', models.SlugField(editable=False, null=True)),
                ('geospace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_demo_1.Geospace')),
            ],
            options={
                'db_table': 'morchas',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('name', models.CharField(max_length=250, verbose_name='name of post')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('slug', models.SlugField(editable=False, null=True)),
                ('geospace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_demo_1.Geospace')),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.AddField(
            model_name='morcha',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morchas', to='api_demo_1.Post'),
        ),
        migrations.AddField(
            model_name='intrusion',
            name='morcha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morcha', to='api_demo_1.Morcha'),
        ),
        migrations.AddField(
            model_name='intrusion',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='api_demo_1.Post'),
        ),
    ]
