# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-14 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_demo_1', '0002_auto_20170211_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intrusion',
            options={},
        ),
        migrations.RemoveField(
            model_name='intrusion',
            name='status',
        ),
        migrations.AlterField(
            model_name='intrusion',
            name='neutralized_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intrusion',
            name='non_human_intrusion_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intrusion',
            name='verified_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
