# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-16 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_demo_1', '0003_auto_20170214_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battalion',
            fields=[
                ('name', models.CharField(max_length=250, verbose_name='Name of Battalion')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('slug', models.SlugField(editable=False, null=True)),
                ('geospace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_demo_1.Geospace')),
            ],
            options={
                'db_table': 'battalions',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='battalion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battalions', to='api_demo_1.Battalion'),
        ),
    ]
