# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-16 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_demo_1', '0004_auto_20170216_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='battalion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='api_demo_1.Battalion'),
        ),
    ]
